### ISSUE TITLE
Coverage report

### ISSUE THREAD

**Issue by andrewgy8** [mercadona/rele#39]
Add some service like coveralls.io? Any other suggestions? Does travis have this integration?

**Comment by cam-barts** [comment]
I use codecov.io. If you'd like, I could set up and integration for you.

**Comment by andrewgy8** [comment]
Hey @cam-barts ! That would be great. 

Just let us know what you need. I suppose we have to install an integration and setup an account.

**Comment by cam-barts** [comment]
It's pretty simple really. If you add me as a collaborator on the project, I can set it up on this instead of on a fork. If i do it on a fork, it will only track my fork on the Readme. If you add me as a collaborator, I should be able to do it on this branch. The flow:
- Set up an account on codecov (I already have one)
- Get the key for the project
- Add a coverage report to CI (travis)
- Send the coverage to codecov in CI (travis)
- Add sweet badge to the Readme

**Comment by andrewgy8** [comment]
@cam-barts Thanks for the contribution offer! @jonasae has taken up the responsibility in #46
